{{- if .Values.curator.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-curator-config
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  action_file.yml: |-
    ---
    # Remember, leave a key empty if there is no value.  None will be a string,
    # not a Python "NoneType"
    #
    # Also remember that all examples have 'disable_action' set to True.  If you
    # want to use this action as a template, be sure to set this to False after
    # copying it.
    actions:
      1:
        action: delete_indices
        description: "Clean up ES by deleting old indices"
        options:
          timeout_override:
          continue_if_exception: False
          disable_action: False
        filters:
        - filtertype: age
          source: name
          direction: older
          timestring: '{{ .Values.curator.age.timestring }}'
          unit: {{ .Values.curator.age.unit }}
          unit_count: {{ .Values.curator.age.unit_count }}
          field:
          stats_result:
          epoch:
          exclude: False

      2:
        action: snapshot
        description: Snapshots selected indices into repository s3-snapshots
        options:
          repository: {{ .Values.curator.snapshot.repository }}
          name:
          disable_action: {{ .Values.curator.snapshot.disabled }}
          ignore_empty_list: {{ .Values.curator.options.ignoreEmptyList }}
          ignore_unavailable: {{ .Values.curator.options.ignoreUnavailable }}
          continue_if_exception: True
          include_global_state: {{ .Values.curator.snapshot.includeGlobalState }}
          wait_for_completion: {{ .Values.curator.snapshot.waitForCompletion }}
          max_wait: {{ .Values.curator.snapshot.maxWait }}
          wait_interval: {{ .Values.curator.snapshot.waitInterval }}
        filters:
        - filtertype: age
          source: name
          direction: older
          timestring: '{{ .Values.curator.snapshot.age.timestring }}'
          unit: {{ .Values.curator.snapshot.age.unit }}
          unit_count: {{ .Values.curator.snapshot.age.unit_count }}
          field:
          stats_result:
          epoch:
          exclude: False

  config.yml: |-
    ---
    # Remember, leave a key empty if there is no value.  None will be a string,
    # not a Python "NoneType"
    client:
      hosts:
        - {{ template "fullname" . }}
      port: {{ .Values.service.httpPort }}
      url_prefix:
      use_ssl: False
      certificate:
      client_cert:
      client_key:
      ssl_no_validate: False
      http_auth:
      timeout: 30
      master_only: False
    logging:
      loglevel: INFO
      logfile:
      logformat: default
      blacklist: ['elasticsearch', 'urllib3']
{{- end }}
